name: gnerate badges

on:
  pull_request:
  push:
    branches:
      - badges

defaults:
  run:
    working-directory: ./dialogPlus

jobs:
  badge:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v3
        id: audit
        with:
          working_directory: ./dialogPlus
          production_flag: true
          json_flag: true
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test
          dedupe_issues: true
      - name: moderate_vulns
        run: echo ::set-output name=moderate ::$(node -e "const audit={{steps.audit.outputs.npm_audit}}; console.log(audit.metadata.vulnerabilities.moderate)")
      - id: moderate-badge
        uses: tagdots/setup-badge-action@663d7a5382b8300caa4492de16e85aa7e4667ef0 # 1.0.3
        with:
          badge-name: mod-vuln
          badge-url: https://raw.githubusercontent.com/tagdots/setup-badge/refs/heads/main/LICENSE
          label: npm-audit moderate vulns
          message: {{ steps.moderate_vulns.outputs.moderate }}
          message-color: FFA500
