name: build release

on:
  pull_request:
  push:
    branches:
      - main
      - '!badges'

defaults:
  run:
    working-directory: ./dialogPlus

jobs:
  badges:
    name: npm audit
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v3
        id: audit
        continue-on-error: true
        with:
          working_directory: ./dialogPlus
          production_flag: true
          json_flag: true
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test
          dedupe_issues: true
      - run: echo ::set-output name=low ::$(node -e "const audit=${{ steps.audit.outputs.npm_audit }}; console.log(audit.metadata.vulnerabilities.low)")
        id: low_vulns
      - name: Low Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_SECRET }}
          gistID: 5ab897e7e447a33d8d01dd678361c14c 
          filename: low.json
          label: low
          message: ${{ steps.low_vulns.outputs.low }}
          color: green
      - run: echo ::set-output name=moderate ::$(node -e "const audit=${{ steps.audit.outputs.npm_audit }}; console.log(audit.metadata.vulnerabilities.moderate)")
        id: moderate_vulns
      - name: Moderate Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_SECRET }}
          gistID: 5ab897e7e447a33d8d01dd678361c14c 
          filename: moderate.json
          label: moderate
          message: ${{ steps.moderate_vulns.outputs.moderate }}
          color: yellow
      - run: echo ::set-output name=high::$(node -e "const audit=${{ steps.audit.outputs.npm_audit }}; console.log(audit.metadata.vulnerabilities.high)")
        id: high_vulns
      - name: High Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_SECRET }}
          gistID: 5ab897e7e447a33d8d01dd678361c14c 
          filename: high.json
          label: high
          message: ${{ steps.high_vulns.outputs.high }}
          color: orange
      - run: echo ::set-output name=critical ::$(node -e "const audit=${{ steps.audit.outputs.npm_audit }}; console.log(audit.metadata.vulnerabilities.critical)")
        id: critical_vulns
      - name: Critical Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_SECRET }}
          gistID: 5ab897e7e447a33d8d01dd678361c14c 
          filename: critical.json
          label: crtitical
          message: ${{ steps.critical_vulns.outputs.critical }}
          color: red


  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: install dependencies
      run: npm install
    - name: build pwa
      run: ./build_pwa.sh
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'iconic_adialogplus_pwa.zip'
        directory: ./dialogPlus
        path: dist
    - run: echo ::set-output name=tag_name::pwa_$(date +%d%m%y%H%M%S)
      id: set_tag_name
    - name: Upload Release
      uses: ncipollo/release-action@v1.20.0
      with:
        artifacts: "./dialogPlus/iconic_adialogplus_pwa.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.set_tag_name.outputs.tag_name }}
